Css two column layout - Jimmy Wu
jameswu49/c1222-code-solutions pull request #23
Opened 2022-12-09 21:34 UTC by jameswu49

![Screenshot 2022-12-09 at 1 33 54 PM](https://user-images.githubusercontent.com/107448164/206799730-239a0b6d-e8f7-4402-b4ce-4a106d1859ca.png)

2022-12-12 23:53 UTC, codingcodymiller requested changes
Hey Jimmy! The text in the main header and subheader of the first row is not centered, and some of your font colors are incorrect as compared to the example. Please revise and submit a new screenshot with your revision.

2022-12-13 03:48 UTC, jameswu49 commented
<img width="1194" alt="Screenshot 2022-12-12 at 7 46 20 PM" src="https://user-images.githubusercontent.com/107448164/207221810-82f81710-f77f-4f62-b4d1-b228329c0a06.png">

2022-12-13 17:34 UTC, codingcodymiller requested changes

2022-12-13 17:34 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
This doesn't add up correctly 👁️ 👁️

2022-12-13 18:43 UTC, codingcodymiller approved these changes

2022-12-13 18:44 UTC, merged